<?php

function unl_tags_menu()
{
  $items = array();

  $items['admin/unl/tags/import'] = array(
    'title' => 'Import UNL Tags',
    'description' => 'Import UNL Tags',
    'access arguments' => array('administer taxonomy'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('unl_tags_import_form'),
    'type' => MENU_NORMAL_ITEM,
  );
  
  return $items;
}

function unl_tags_import_form($form, &$form_state) {
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Import Tags'),
  );
  return $form;
}

function unl_tags_import_form_submit($form, &$form_state) {
  $url = 'https://raw.githubusercontent.com/unl/tags/master/data/flat.json';

  $tags = file_get_contents($url);

  if (!$tags) {
    drupal_set_message(t('Unable to get the tags.', [], 'error'));
    $form_state['redirect'] = 'admin/unl/tags/impor';
    return $form;
  }

  $tags = json_decode($tags, true);

  if (!$tags || empty($tags)) {
    drupal_set_message(t('Tags could not be json_decoded', [], 'error'));
    $form_state['redirect'] = 'admin/unl/tags/impor';
    return $form;
  }

  if (!$vocab = taxonomy_vocabulary_machine_name_load('unl_tags')) {
    // Create it.
    $new_vocab = (object) array(
      'name' => 'UNL Tags',
      'description' => 'UNL controlled vocabulary',
      'machine_name' => 'unl_tags',
    );
    
    //save it
    taxonomy_vocabulary_save($new_vocab);

    //now get it
    $vocab = taxonomy_vocabulary_machine_name_load('unl_tags');
  }

  $added = 0;
  $updated = 0;
  $removed = 0;

  $existing = taxonomy_get_tree($vocab->vid, 0, 1);

  foreach ($existing as $term) {
    $machineName = $machine_name = $term->machine_name;
    
    if (!isset($tags[$machineName])) {
      taxonomy_term_delete($term->tid);
      $removed++;
    }
  }

  foreach ($tags as $machineName=>$humanName) {
    $term_existing = taxonomy_term_machine_name_load($machineName, $vocab->machine_name);

    if ($term_existing === false) {
      $new_term = taxonomy_term_save(
        (object) ['name' => $humanName, 'vid' => $vocab->vid, 'machine_name'=>$machineName]
      );
      $added++;
    }
    else {
      if (is_array($term_existing)) {
        $term = $term_existing[0];
      }
      else {
        $term = $term_existing;
      }

      if (trim($term->name) != trim($humanName)) {
        //Update the human name
        $term->name = $humanName;
        taxonomy_term_save($term);
        $updated++;
      }
    }
    
  }

  drupal_set_message(t('Tags have been imported. @added added, @updated updated, and @removed removed.', ['@added' => $added, '@updated' => $updated, '@removed' => $removed]));

  return $form_state['redirect'] = 'admin/structure/taxonomy/unl_tags/';
}
